### ISSUE TITLE
bluez snap for core16 (core)

### ISSUE THREAD

**Issue by ZmRZjFuDsDiR4qi5801F** [canonical/bluez-snap#10]
Hello bluez-snap team, my 6 year old hardware is based on ubuntu core 16 and I had some bluetooth devices connected to it. 
Because I had to flash the device with a original image I lost the deprecated bluez snap. 

So I would like to kindly ask you for the latest bluez snap for Ubuntu core 16 from your history, based on just core, not core20 or even core22.  Probably you can find it in your internal archive and you could share it with me.  
I appreciate any answer. 

Thank you in advance.

**Comment by alfonsosanchezbeato** [comment]
Hi, the core snap based bluez is still available, you can install with `snap install --channel=latest/stable bluez`. If you don't specify the channel, it will use `22/stable` by default these days. (yes, that the old channel is named `latest` is unfortunate, but we cannot change that at the moment).

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
Hi, your response was very useful to me and solved my issue: My app is running again. 
Thanx a lot and have a nice day.
